export const LOAD_APP = 'LOAD_APP';
export const LOAD_APP_ATTEMPT = 'LOAD_APP_ATTEMPT';
export const LOAD_APP_SUCCESS = 'LOAD_APP_SUCCESS';
export const LOAD_APP_FAIL = 'LOAD_APP_FAIL';

export const LOAD_REACT_PORTFOLIO_ATTEMPT = 'LOAD_REACT_PORTFOLIO_ATTEMPT';
export const LOAD_REACT_PORTFOLIO_SUCCESS = 'LOAD_REACT_PORTFOLIO_SUCCESS';
export const LOAD_REACT_PORTFOLIO_FAIL = 'LOAD_REACT_PORTFOLIO_FAIL';

export const TOGGLE_REACT_PORTFOLIO_MENU = 'TOGGLE_REACT_PORTFOLIO_MENU';
export const TOGGLE_REACT_PORTFOLIO_SUBMENU = 'TOGGLE_REACT_PORTFOLIO_SUBMENU';